# SPDX-FileCopyrightText: 2024 Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Run Promtail installation tasks
  tags:
    - setup-all
    - setup-promtail
    - install-all
    - install-promtail
  block:
    - when: promtail_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: promtail_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Run Promtail uninstallation tasks
  tags:
    - setup-all
    - setup-promtail
  block:
    - when: not promtail_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
